In [53]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [54]:
a = [10,56,78,10]
b = [90,23,64,37]

In [55]:
arr1 = np.array(distances)
arr1
arr2 = np.array(speeds)
arr2

array([10, 56, 78, 10])

array([90, 23, 64, 37])

In [56]:
arr1.shape # Rows and columns 

arr1.size # Number of elements

arr1.dtype # Data type of elements

(4,)

4

dtype('int32')

### Data hierarchy

- Object (Most cases is a string)
- Float
- Integer
<br />

**If a numpy array contains just one value of 1 object data type, the array's type is object**
<br />
**If a numpy array contains just one value of 1 float data type and no value of object data type, the array's type is float**
<br />
**If a numpy array contains just one value of 1 int data type and no value of object data type and no value of float data type, the array's type is int**

In [57]:
obj = np.array([1,2,1.23,97.21,"Hello!"])
obj.dtype # If the returned value contains "U", it is an object

flt = np.array([1,2,1.23,97,10])
flt.dtype 

it = np.array([1,2,13,97,10])
it.dtype 

dtype('<U32')

dtype('float64')

dtype('int32')

In [58]:
n = 10
a = np.arange(n) # Creates an array which has elements from 0 to n-1
a

start = 5
stop = 55
inc = 5
a2 = np.arange(start,stop,inc) # Creates an array which has elements from start to stop-1 
# After each iteration, the element in incremented by dec until it is greater than stop

a2

start = 100
stop = 20
dec = -10
a3 = np.arange(start,stop,dec) # Creates an array which has elements from start to stop-1 
# After each iteration, the element in decremented by dec until it is lesser than stop
a3

start = 10
stop = 100
n = 7
l = np.linspace(start,stop,n) # Returns n elements from start to stop, including them
# Wheer the difference between an element and the next are same in all cases
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

array([100,  90,  80,  70,  60,  50,  40,  30])

array([ 10.,  25.,  40.,  55.,  70.,  85., 100.])

In [59]:
n1 = np.array([1,2,3,4,5])
n2 = np.array([10,20,30,40,50])

s = n1+n2 # Add each element in n1 with the corresponding element in n2. The number of elements should be the same
s

d = n2-n1 # Subtract each element in n1 from the corresponding element in n2. The number of elements should be the same
d

p = n1*n2 # Multiple each element in n1 with the corresponding element in n2. The number of elements should be the same
p

q = n2/n1 # Divide each element in n2 by the corresponding element in n1. The number of elements should be the same
q

n1.sum() # Sum of all elements in the array

array([11, 22, 33, 44, 55])

array([ 9, 18, 27, 36, 45])

array([ 10,  40,  90, 160, 250])

array([10., 10., 10., 10., 10.])

15

In [95]:
a = [39,46,50,66,67,76,88,90,108,108,116,127,129,131,143,144]
arr = np.array(a)

rws = 8
col = 2

d2 = arr.reshape(rws,col) # rws is the number of rows and col is the number of columns. This will make the array a 2D one 
d2
d2.size
d2.shape

n = 2
rws = 4
el = 2

d3 = arr.reshape(n,rws,el) # Making a 3d array
# n refers to the number of arrays which will be created
# rws is the number of rows per array. They are mini arrays within the array
# el is the number of elements per row
d3
d3.size
d3.shape

array([[ 39,  46],
       [ 50,  66],
       [ 67,  76],
       [ 88,  90],
       [108, 108],
       [116, 127],
       [129, 131],
       [143, 144]])

16

(8, 2)

39

array([[[ 39,  46],
        [ 50,  66],
        [ 67,  76],
        [ 88,  90]],

       [[108, 108],
        [116, 127],
        [129, 131],
        [143, 144]]])

16

(2, 4, 2)

array([39, 46])

In [81]:
grt = (arr > 20)
grt

arr[grt]

even = (arr % 2 == 0)
even

arr[even]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

array([ 39,  46,  50,  66,  67,  76,  88,  90, 108, 108, 116, 127, 129,
       131, 143, 144])

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False, False, False, False,  True])

array([ 46,  50,  66,  76,  88,  90, 108, 108, 116, 144])

In [86]:
n = 20
np.zeros(n) # Create a 1D array which has n zeros

np.zeros(n)+10 # Create a 1D array which has n 10s

r = 2
c = 10
np.zeros((r,c)) # Create a 2D array of ones which has r rows and c columns

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10.])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
n = 20
np.ones(n) # Create a 1D array which has n ones

np.ones(n)+10 # Create a 1D array which has n 11s

r = 2
c = 10
np.ones((r,c)) # Create a 2D array of ones which has r rows and c columns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

array([11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11.,
       11., 11., 11., 11., 11., 11., 11.])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [98]:
n = 5
i = np.eye(5) # Creates an identity matrix which has 5 elements per row 
# It is a square matrix (rows=columns) in which there is a diagonal of n 1s and the other elements are 0s
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
np.diag(i) # Gets the primary diagonal of the matrix

array([1., 1., 1., 1., 1.])

In [108]:
arr[0] # Selecting element from 1D array
d2[1][0] # Selecting element from 2D array
d3[1][3][1] # Selecting element from 3D array

arr[0] = 100 # Updating element in 1D array
d2[1][0] = 200 # Updating element in 2D array
d3[1][3][1] = 300 # Updating element in 3D array

arr
d2
d3

arr = np.delete(arr,0) # Deleting element from 1D array

arr

46

67

300

array([100, 200,  66,  67,  76,  88,  90, 108, 108, 116, 127, 129, 131,
       143, 300])

array([[100,  46],
       [200,  76],
       [ 88,  90],
       [108, 108],
       [116, 127],
       [129, 131],
       [143, 300]])

array([[[100,  46],
        [200,  66],
        [ 67,  76],
        [ 88,  90]],

       [[108, 108],
        [116, 127],
        [129, 131],
        [143, 300]]])

array([200,  66,  67,  76,  88,  90, 108, 108, 116, 127, 129, 131, 143,
       300])

In [110]:
arr.sort() # Sort the array
arr

array([ 66,  67,  76,  88,  90, 108, 108, 116, 127, 129, 131, 143, 200,
       300])

In [112]:
arr.min() # Min value in array
arr.max() # Max value in array
arr.mean() # Mean of values in array
d2.transpose() # The rows become columns and columns beco

66

300

124.92857142857143

array([[100, 200,  88, 108, 116, 129, 143],
       [ 46,  76,  90, 108, 127, 131, 300]])