In [74]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [75]:
a = [10,56,78,10]
b = [90,23,64,37]

In [76]:
arr1 = np.array(a)
arr1
arr2 = np.array(b)
arr2

array([10, 56, 78, 10])

array([90, 23, 64, 37])

In [77]:
arr1.shape # Rows and columns 

arr1.size # Number of elements

arr1.dtype # Data type of elements

(4,)

4

dtype('int32')

In [78]:
d1 = np.array([1,2,3,4,5]) # 1D Array
d1

d2 = np.array([ # 2D Array
    [1,2,3],
    [192,27,28],
    [182,276,128]
])
d2

d3 = np.array([ # 3D Array
    [
        [1,2],
        [3,4],
        [5,6]
    ],
    
    [
        [7,8],
        [9,10],
        [11,12]
    ]
])
d3

array([1, 2, 3, 4, 5])

array([[  1,   2,   3],
       [192,  27,  28],
       [182, 276, 128]])

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

### Note
**In 2D arrays, axis 0 is the Y axis aka columns**
<br />
**axis 1 is the X axis aka rows**

### Data hierarchy

- Object (Most cases is a string)
- Float
- Integer
<br />

**If a numpy array contains just one value of 1 object data type, the array's type is object**
<br />
**If a numpy array contains just one value of 1 float data type and no value of object data type, the array's type is float**
<br />
**If a numpy array contains just one value of 1 int data type and no value of object data type and no value of float data type, the array's type is int**

In [79]:
obj = np.array([1,2,1.23,97.21,"Hello!"])
obj.dtype # If the returned value contains "U", it is an object

flt = np.array([1,2,1.23,97,10])
flt.dtype 

it = np.array([1,2,13,97,10])
it.dtype 

dtype('<U32')

dtype('float64')

dtype('int32')

In [80]:
n = 10
a = np.arange(n) # Creates an array which has elements from 0 to n-1
a

start = 1
stop = 10
a = np.arange(start,stop) # Creates an array which has elements from start to stop-1
a

start = 5
stop = 55
inc = 5
a2 = np.arange(start,stop,inc) # Creates an array which has elements from start to stop-1 
# After each iteration, the element in incremented by dec until it is greater than stop

a2

start = 100
stop = 20
dec = -10
a3 = np.arange(start,stop,dec) # Creates an array which has elements from start to stop-1 
# After each iteration, the element in decremented by dec until it is lesser than stop
a3

start = 10
stop = 100
n = 7
l = np.linspace(start,stop,n) # Returns n elements from start to stop, including them
# Wheer the difference between an element and the next are same in all cases
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

array([100,  90,  80,  70,  60,  50,  40,  30])

array([ 10.,  25.,  40.,  55.,  70.,  85., 100.])

In [81]:
n1 = np.array([1,2,3,4,5])
n2 = np.array([10,20,30,40,50])

s = n1+n2 # Add each element in n1 with the corresponding element in n2. The number of elements should be the same
s

d = n2-n1 # Subtract each element in n1 from the corresponding element in n2. The number of elements should be the same
d

p = n1*n2 # Multiple each element in n1 with the corresponding element in n2. The number of elements should be the same
p

q = n2/n1 # Divide each element in n2 by the corresponding element in n1. The number of elements should be the same
q

n1.sum() # Sum of all elements in the array

array([11, 22, 33, 44, 55])

array([ 9, 18, 27, 36, 45])

array([ 10,  40,  90, 160, 250])

array([10., 10., 10., 10., 10.])

15

In [82]:
arr.min() # Min value in array
arr.argmin() # Index of the min value in the array

arr.max() # Max value in array
arr.argmax() # Index of the max value in the array

arr.mean() # Mean of values in array

46

0

300

14

119.66666666666667

In [83]:
d2.sum(axis = 0) # Sum of the elements in each column
d2.sum(axis = 1) # Sum of the elements in each row

d2.max(axis = 0) # Max element in each column
d2.max(axis = 1) # Max element in each row

d2.min(axis = 0) # Min element in each column
d2.min(axis = 1) # Min element in each row

d2.mean(axis = 0) # Mean of the elements in each column
d2.mean(axis = 1) # Mean of the elements in each row

array([375, 305, 159])

array([  6, 247, 586])

array([192, 276, 128])

array([  3, 192, 276])

array([1, 2, 3])

array([  1,  27, 128])

array([125.        , 101.66666667,  53.        ])

array([  2.        ,  82.33333333, 195.33333333])

In [84]:
a = [39,46,50,66,67,76,88,90,108,108,116,127,129,131,143,144]
arr = np.array(a)

rws = 8
col = 2

d2 = arr.reshape(rws,col) # rws is the number of rows and col is the number of columns. This will make the array a 2D one 
d2
d2.size
d2.shape

n = 2
rws = 4
el = 2

d3 = arr.reshape(n,rws,el) # Making a 3d array
# n refers to the number of arrays which will be created
# rws is the number of rows per array. They are mini arrays within the array
# el is the number of elements per row
d3
d3.size
d3.shape

d3.ravel() # Convert 2D/3D array to a 1D array

array([[ 39,  46],
       [ 50,  66],
       [ 67,  76],
       [ 88,  90],
       [108, 108],
       [116, 127],
       [129, 131],
       [143, 144]])

16

(8, 2)

array([[[ 39,  46],
        [ 50,  66],
        [ 67,  76],
        [ 88,  90]],

       [[108, 108],
        [116, 127],
        [129, 131],
        [143, 144]]])

16

(2, 4, 2)

array([ 39,  46,  50,  66,  67,  76,  88,  90, 108, 108, 116, 127, 129,
       131, 143, 144])

In [85]:
grt = (arr > 20)
grt

arr[grt]

even = (arr % 2 == 0)
even

arr[even]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

array([ 39,  46,  50,  66,  67,  76,  88,  90, 108, 108, 116, 127, 129,
       131, 143, 144])

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False, False, False, False,  True])

array([ 46,  50,  66,  76,  88,  90, 108, 108, 116, 144])

In [86]:
n = 20
np.zeros(n) # Create a 1D array which has n zeros

np.zeros(n)+10 # Create a 1D array which has n 10s

r = 2
c = 10
np.zeros((r,c)) # Create a 2D array of ones which has r rows and c columns

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10.])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
n = 20
np.ones(n) # Create a 1D array which has n ones

np.ones(n)+10 # Create a 1D array which has n 11s

r = 2
c = 10
np.ones((r,c)) # Create a 2D array of ones which has r rows and c columns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

array([11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11.,
       11., 11., 11., 11., 11., 11., 11.])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [88]:
n = 20
np.empty(n) # Create a 1D array which has n random elements

r = 2
c = 10
np.empty((r,c)) # Create a 2D array of random elements which has r rows and c columns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [89]:
n = 5
i = np.eye(5) # Creates an identity matrix which has 5 elements per row 
# It is a square matrix (rows=columns) in which there is a diagonal of n 1s and the other elements are 0s
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [90]:
np.diag(i) # Gets the primary diagonal of the matrix

array([1., 1., 1., 1., 1.])

In [91]:
arr[0] # Selecting element from 1D array
d2[1][0] # Selecting element from 2D array
d3[1][3][1] # Selecting element from 3D array

arr[0] = 100 # Updating element in 1D array
d2[1][0] = 200 # Updating element in 2D array
d3[1][3][1] = 300 # Updating element in 3D array

arr
d2
d3

arr = np.delete(arr,0) # Deleting element from 1D array

arr

39

50

144

array([100,  46, 200,  66,  67,  76,  88,  90, 108, 108, 116, 127, 129,
       131, 143, 300])

array([[100,  46],
       [200,  66],
       [ 67,  76],
       [ 88,  90],
       [108, 108],
       [116, 127],
       [129, 131],
       [143, 300]])

array([[[100,  46],
        [200,  66],
        [ 67,  76],
        [ 88,  90]],

       [[108, 108],
        [116, 127],
        [129, 131],
        [143, 300]]])

array([ 46, 200,  66,  67,  76,  88,  90, 108, 108, 116, 127, 129, 131,
       143, 300])

In [92]:
arr.argsort() # Indexes of the elements of the current array that would make the array a sorted one 

arr.sort() # Sort the array
arr

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  1, 14],
      dtype=int64)

array([ 46,  66,  67,  76,  88,  90, 108, 108, 116, 127, 129, 131, 143,
       200, 300])

In [93]:
d2.transpose() # The rows become columns and columns become rows. Only works in 2D arrays

array([[100, 200,  67,  88, 108, 116, 129, 143],
       [ 46,  66,  76,  90, 108, 127, 131, 300]])

In [94]:
for i in arr.flat:
    print(i) # Print all elements of the array

46
66
67
76
88
90
108
108
116
127
129
131
143
200
300


In [95]:
arr.ndim # Number of dimensions
d3.ndim

1

3

In [96]:
arr.nbytes # Number of bytes used by the elements in memory

60

In [97]:
np.where(arr > 100) # Indexes of the elements whose value is greater than 100

np.where(arr == 46) # Indexes of the elements whose value is greater than 46

# You can perform more conditions and even use logical operators (& and |)

(array([ 6,  7,  8,  9, 10, 11, 12, 13, 14], dtype=int64),)

(array([0], dtype=int64),)

In [98]:
np.count_nonzero(arr) # Number of elements which are not 0

15